-- ALTER TABLE `menu_beverage` AUTO_INCREMENT = 0;
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通紅茶', 25);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通綠茶', 25);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通麥茶', 25);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通烏龍茶', 35);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通奶茶', 35);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (7, '普通四季春茶', 55);

INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (8, '超淺紅茶', 35);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (8, '超淺綠茶', 35);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (8, '超淺麥茶', 35);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (8, '超淺烏龍茶', 45);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (8, '超淺奶茶', 45);

INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深紅茶', 5);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深綠茶', 5);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深麥茶', 5);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深烏龍茶', 15);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深奶茶', 15);
INSERT INTO `menu_beverage`(`u_id`, `b_name`, `price`) VALUES (9, '超深四季春茶', 35);
-- ALTER TABLE `ice_type`
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('18','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('18','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('18','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('18','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('18','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('19','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('19','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('19','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('19','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('19','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('20','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('20','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('20','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('20','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('20','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('21','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('21','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('21','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('21','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('21','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('22','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('22','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('22','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('22','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('22','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('23','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('23','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('23','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('23','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('23','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('24','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('24','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('24','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('24','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('24','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('25','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('25','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('25','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('25','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('25','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('26','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('26','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('26','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('26','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('26','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('27','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('27','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('27','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('27','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('27','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('28','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('28','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('28','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('28','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('28','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('29','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('29','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('29','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('29','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('29','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('30','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('30','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('30','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('30','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('30','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('31','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('31','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('31','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('31','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('31','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('32','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('32','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('32','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('32','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('32','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('33','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('33','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('33','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('33','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('33','10');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('34','0');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('34','3');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('34','5');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('34','7');
INSERT INTO `ice_type`(`b_id`, `ice_value`) VALUES ('34','10');
-- ALTER TABLE `sugar_type`
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('18','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('18','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('18','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('18','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('18','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('19','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('19','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('19','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('19','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('19','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('20','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('20','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('20','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('20','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('20','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('21','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('21','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('21','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('21','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('21','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('22','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('22','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('22','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('22','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('22','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('23','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('23','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('23','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('23','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('23','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('24','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('24','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('24','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('24','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('24','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('25','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('25','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('25','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('25','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('25','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('26','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('26','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('26','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('26','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('26','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('27','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('27','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('27','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('27','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('27','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('28','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('28','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('28','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('28','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('28','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('29','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('29','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('29','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('29','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('29','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('30','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('30','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('30','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('30','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('30','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('31','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('31','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('31','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('31','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('31','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('32','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('32','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('32','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('32','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('32','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('33','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('33','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('33','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('33','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('33','10');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('34','0');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('34','3');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('34','5');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('34','7');
INSERT INTO `sugar_type`(`b_id`, `sugar_value`) VALUES ('34','10');
-- ALTER TABLE `order`
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (1, 7, '2022-06-19 24:20:25' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (2, 8, '2022-06-03 07:53:32' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (1, 7, '2022-06-05 20:36:00' , 'Y' , '2022-06-05 20:37:12');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (1, 8, '2022-06-08 10:03:43' , 'Y' , '2022-06-08 10:04:51');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (2, 8, '2022-06-08 18:43:23' , 'Y' , '2022-06-08 18:44:55');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (2, 9, '2022-06-08 22:48:41' , 'Y' , '2022-06-08 22:49:00');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (2, 7, '2022-06-10 24:41:32' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (1, 9, '2022-06-11 15:51:11' , 'Y' , '2022-06-11 15:53:54');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (3, 8, '2022-06-11 18:38:52' , 'Y' , '2022-06-11 18:39:50');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (3, 7, '2022-06-17 06:47:43' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (3, 9, '2022-06-19 18:09:50' , 'Y' , '2022-06-19 18:11:20');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (3, 7, '2022-06-20 05:28:25' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (3, 9, '2022-06-21 00:20:34' , NULL , NULL);
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (2, 9, '2022-06-21 15:37:01' , 'Y' , '2022-05-21 15:40:02');
INSERT INTO `orders`(`c_id`, `m_id`, `order_time`, `is_accepted`, `accepted_time`) VALUES (1, 9, '2022-06-26 20:13:11' , 'Y' , '2022-05-26 20:14:26');
-- ALTER TABLE `order_beberage`
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('20','21','5','3','4');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('20','25','5','3','3');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('21','33','3','7','1');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('22','18','10','10','2');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('22','20','0','0','1');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('22','31','7','5','5');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('23','29','3','5','2');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('24','24','3','3','2');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('24','27','5','5','7');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('25','19','3','10','3');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('26','23','7','7','1');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('26','31','10','10','4');

INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('27','22','3','5','2');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('27','26','5','3','6');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('28','23','10','10','4');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('29','30','0','7','7');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('29','34','7','7','3');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('29','28','3','3','5');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('29','29','7','5','8');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('30','32','5','5','2');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('31','18','10','3','7');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('32','26','0','10','4');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('32','24','7','5','1');
INSERT INTO `order_beverage`(`o_id`, `b_id`, `sugar`, `ice`, `quantity`) VALUES ('33','34','5','7','4');
--ALTER TABLE `comment`
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('1','7','4','尚可','2022-05-01 06:02:11');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('1','8','3','差強人意','2022-05-05 20:40:49');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('1','9','4','可','2022-05-05 20:40:49');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('2','7','5','好喝','2022-05-08 07:43:39');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('2','8','2','有點糟','2022-05-12 10:08:46');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('2','9','4','還不錯喝','2022-05-16 16:41:36');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('3','7','0','可以關了','2022-05-21 22:16:57');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('3','8','3','差強人意','2022-05-27 20:46:09');
INSERT INTO `comments`(`c_id`, `m_id`, `stars`, `content`, `time`) VALUES ('3','9','4','還行吧','2022-05-30 07:54:35');
